import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="flex items-center justify-center h-[calc(100vh-110px)] ">
        <div className="relative flex flex-col m-6 space-y-8 bg-white shadow-md rounded-2xl md:flex-row md:space-y-0 min-h-[480px]">
          {/* <!-- left side --> */}
          <div>
            <img
              src="/promo1.jpg"
              alt="img"
              className="w-[500px] h-full hidden rounded-l-2xl md:block object-cover"
            />
          </div>
          {/* <!-- right side --> */}
          <div className="relative min-w-[200px]">{children}</div>
        </div>
      </div>
    </div>
  );
}
