// Packages
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";

// Local Imports
import { auth } from "@/auth";
import { getSubjects } from "@/hooks/get-subjects";
import NProgress from "@/providers/NProgress";
import { SonnerToastProvider } from "@/providers/sonner-toast-provider";
import "./globals.css";
const Navbar = dynamic(() => import("@/components/navbar/navbar"));
const Footer = dynamic(() => import("@/components/footer"));

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Ruhani Quiz",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await auth();
    const subjects = await getSubjects();

    return (
        <SessionProvider session={session}>
            <html lang="en">
                <body className={inter.className}>
                    <SonnerToastProvider />
                    <NProgress />
                    <Navbar subjects={subjects} />
                    <main>{children}</main>
                    <Footer />
                </body>
            </html>
        </SessionProvider>
    );
}
